# This is a configuration file
[login info]    # section name
# key - value pairs
base_URL = https://opensource-demo.orangehrmlive.com/
username = Admin
password = admin123
invalid_username = Admin123